# advanced analytics using statistics

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
x1 = list(range(20))
print(x1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


np.arange -- np array

In [ ]:
r1 = np.arange(5)
r1

array([0, 1, 2, 3, 4])

In [ ]:

r2 = np.arange(5,10)
r2

array([5, 6, 7, 8, 9])

In [ ]:
r2[3]

8

In [ ]:
r3 = np.arange(3,10)
r3[4]


7

In [ ]:
r4 = np.arange(4,20,4)
r4[-1]

16

In [ ]:
r5 = np.arange(20,7,-4)

In [ ]:
r5

array([20, 16, 12,  8])

In [ ]:
r6 = np.array ([12,3,53,2,2,55,64,64])

In [ ]:
r6[2]

53

In [ ]:
r6[-4:-1]

array([ 2, 55, 64])

- add an element to array

In [ ]:
r6 = np.append(r3,99)

In [ ]:
r6

array([ 3,  4,  5,  6,  7,  8,  9, 99])

- add two arrays

In [ ]:
r7 = np.concatenate((r3,r4))

In [ ]:
r7

array([ 3,  4,  5,  6,  7,  8,  9,  4,  8, 12, 16])

insert element at index of your choice

In [ ]:
r3 = np.insert(r3,4,10)
r3

array([ 3,  4,  5,  6, 10, 10,  7,  8,  9])

In [ ]:
r3 = np.insert(r3,5,r1)

In [ ]:
r3

array([ 3,  4,  5,  6, 10,  0,  1,  2,  3,  4, 10,  7,  8,  9])

delete an element from array at an index

In [ ]:
  r8=np.delete(r3,4)

In [ ]:
r8

array([ 3,  4,  5,  6,  0,  1,  2,  3,  4, 10,  7,  8,  9])

## Two dim array

In [ ]:
w1 = [4,5,6,7,8]
w2 = [3,4,4,6,3]


In [ ]:
ar1 = np.array([w1,w2])
ar1

array([[4, 5, 6, 7, 8],
       [3, 4, 4, 6, 3]])

In [ ]:
ar1[0]

array([4, 5, 6, 7, 8])

In [ ]:
ar1[0][2]

6

In [ ]:
ar1[:,3]

array([7, 6])

In [ ]:
x1 = np.array([1,2,4,2,4,24,5,6,7,8,432,3])

len(x1)

12

In [ ]:
ar4 =x1.reshape(4,3)
ar4

array([[  1,   2,   4],
       [  2,   4,  24],
       [  5,   6,   7],
       [  8, 432,   3]])

- add an array to an existing 2dim array

In [ ]:
ar5 = [3,4,5,3,6]

ar6 = np.vstack([ar1,ar5])
ar6

array([[4, 5, 6, 7, 8],
       [3, 4, 4, 6, 3],
       [3, 4, 5, 3, 6]])

In [ ]:
ar7 = np.array([4,3,2])

ar7 = ar7.reshape(3,1)

In [ ]:
ar7

array([[4],
       [3],
       [2]])

In [ ]:
ar6 = np.hstack([ar6,ar7])

In [ ]:
ar6

array([[4, 5, 6, 7, 8, 4],
       [3, 4, 4, 6, 3, 3],
       [3, 4, 5, 3, 6, 2]])

In [ ]:
ar9 = np.array([4,5,6])
ar10 = np.column_stack((ar6,ar9))
ar10

array([[4, 5, 6, 7, 8, 4, 4],
       [3, 4, 4, 6, 3, 3, 5],
       [3, 4, 5, 3, 6, 2, 6]])

In [ ]:
ar10 [:,4]

array([8, 3, 6])

In [ ]:
ar10[:,[1,5]]

array([[5, 4],
       [4, 3],
       [4, 2]])

In [ ]:
ar12 = ar10[:,:3]
ar12

array([[4, 5, 6],
       [3, 4, 4],
       [3, 4, 5]])

In [ ]:
ar13 = np.array([1,3,4])
ar13 = ar13.reshape(3,1)
ar13

array([[1],
       [3],
       [4]])

In [ ]:
ar12 = np.hstack([ar12,ar13])
ar12

array([[4, 5, 6, 7, 1],
       [3, 4, 4, 6, 3],
       [3, 4, 5, 3, 4]])

In [ ]:
ar14 = ar10[:,[4,5,6]]
ar14

array([[8, 4, 4],
       [3, 3, 5],
       [6, 2, 6]])

In [ ]:
ar15= np.hstack([ar12,ar14])
ar15

array([[4, 5, 6, 7, 1, 8, 4, 4],
       [3, 4, 4, 6, 3, 3, 3, 5],
       [3, 4, 5, 3, 4, 6, 2, 6]])

In [ ]:

np.insert(ar15,4,[1,3,5],axis=1)

array([[4, 5, 6, 7, 1, 1, 8, 4, 4],
       [3, 4, 4, 6, 3, 3, 3, 3, 5],
       [3, 4, 5, 3, 5, 4, 6, 2, 6]])

In [ ]:
an= np.insert(ar15,3,[1,2,3,4,5,4,4,5],axis=0)
an


array([[4, 5, 6, 7, 1, 8, 4, 4],
       [3, 4, 4, 6, 3, 3, 3, 5],
       [3, 4, 5, 3, 4, 6, 2, 6],
       [1, 2, 3, 4, 5, 4, 4, 5]])

In [ ]:
np.delete(ar1,(1,4),axis=1)

array([[4, 6, 7],
       [3, 4, 6]])

## numpy part 2

In [ ]:
a1 = np.array([3,3,4,2,5,6,81,3,5,9,3,4])

np.sort(a1)

array([ 2,  3,  3,  3,  3,  4,  4,  5,  5,  6,  9, 81])

In [ ]:
a2 = a1.reshape(3,4)

In [ ]:
a2

array([[ 3,  3,  4,  2],
       [ 5,  6, 81,  3],
       [ 5,  9,  3,  4]])

In [ ]:
np.sort(a2,axis=0)

array([[ 3,  3,  3,  2],
       [ 5,  6,  4,  3],
       [ 5,  9, 81,  4]])

In [ ]:
np.sort(a2,axis=1)

array([[ 2,  3,  3,  4],
       [ 3,  5,  6, 81],
       [ 3,  4,  5,  9]])

- index where cndition is satisfied .
- input to the where command is the condition that needs to be checked .
- output of the where command are the indices where the condition is found to be true .

In [ ]:
x1 = np.array([3,2,5,7,8,6,8,6,5,7,3,5,2,6,5,5,6,2,2,5])

In [ ]:
t1 = np.where(x1<4)
t1

(array([ 0,  1, 10, 12, 17, 18]),)

In [ ]:
len(t1)

1

In [ ]:
len(t1[0])

6

In [ ]:
t1[0][1]

1

- where are the values which meet a criteria

- whre are the values which meet a criteria


- how many values meet a criteria

In [ ]:
x1 = np.array([2,3,5,8,8,9,7])

q1 = np.where(x1<4)

In [ ]:
q1

(array([0, 1]),)

In [ ]:
x1[q1]

array([2, 3])

In [ ]:
len(q1[0])

2

In [ ]:
x2 = np.array([2,4,3,4,5,6,7,6,8,9])

In [ ]:
q1 = np.where(x2%2 ==0)

In [ ]:
q1

(array([0, 1, 3, 5, 7, 8]),)

In [ ]:
x2[q1]

array([2, 4, 4, 6, 6, 8])

In [ ]:
q2 = np.where(x2%2 !=0)
q2

(array([2, 4, 6, 9]),)

In [ ]:
x2[q2]

array([3, 5, 7, 9])

In [ ]:
ar4 = np.array([2,2,3,4,5,6,8,9,7,32,5,7])
len(ar4)

12

In [ ]:
ar4 =ar4.reshape(4,3)
ar4

array([[ 2,  2,  3],
       [ 4,  5,  6],
       [ 8,  9,  7],
       [32,  5,  7]])

In [ ]:
q3 = np.where(ar4<4)

In [ ]:
ar4[q3]

array([2, 2, 3])

## Day Two

## pandas

1. dtwo data structure
      - series
      - dataframe

In [1]:
x1 = [3,6,5,7]

p1 = pd.Series(x1)

NameError: name 'pd' is not defined

In [ ]:
p1

0    3
1    6
2    5
3    7
dtype: int64

In [2]:
p = pd.Series(x1,index=['A','B','C','D'])

p['B']

NameError: name 'pd' is not defined

In [ ]:
k1 = {'virat':1234 , 'rahul':1342 , 'dhoni':123}



In [ ]:
p2 = pd.Series(k1)

In [ ]:
p2

virat    1234
rahul    1342
dhoni     123
dtype: int64

In [5]:
pnew = pd.Series([1212,3223], index = ['rohit','bhumra'])
pnew

NameError: name 'pd' is not defined

In [ ]:

# Create two Series
s1 = pd.Series([1, 2, 3])
s2 = pd.Series([4, 5, 6])

# Concatenate s1 and s2
s3 = pd.concat([s1, s2])

print(s3)


0    1
1    2
2    3
0    4
1    5
2    6
dtype: int64


In [ ]:
pnew.drop(['rohit'])

bhumra    3223
dtype: int64

- Dataframe

-

In [ ]:
e1 = [['amit','mumbai',23],['justin','california',400],['jason','sf',80]]

emp_df = pd.DataFrame(e1,columns = ['name','location','salary'])
emp_df

name    location  salary
0    amit      mumbai      23
1  justin  california     400
2   jason          sf      80

- option for custom index available
- suggested not to use custom index in pd dataframe

In [ ]:

temp = pd.DataFrame(e1,columns = ['name','location','salary'],index = [12,22,33])
temp

name    location  salary
12    amit      mumbai      23
22  justin  california     400
33   jason          sf      80

In [ ]:
emp_df.iat[1,2] = 500

In [ ]:
emp_df

name    location  salary
0    amit      mumbai      23
1  justin  california     500
2   jason          sf      80

In [ ]:
emp_df.at[1,'location']

'california'

In [ ]:
newdf = pd.DataFrame([['abhijit','atlanta',300],['karan','roha',4],['rishabh','bihar',2]])

In [ ]:
newdf

0        1    2
0  abhijit  atlanta  300
1    karan     roha    4
2  rishabh    bihar    2

In [ ]:
emp_df = emp_df._append(newdf)

- **Note**
    - **remember**
    - column names in 2nd dataframe not mentioned
    - pandas doesnt give error
    - it will assume default col names 0,1,2 ...

In [ ]:
emp_df

name    location  salary        0        1      2
0    amit      mumbai    23.0      NaN      NaN    NaN
1  justin  california   500.0      NaN      NaN    NaN
2   jason          sf    80.0      NaN      NaN    NaN
0     NaN         NaN     NaN  abhijit  atlanta  300.0
1     NaN         NaN     NaN    karan     roha    4.0
2     NaN         NaN     NaN  rishabh    bihar    2.0

In [ ]:
emp_df.shape

(6, 6)

In [ ]:
emp_df.index = range(emp_df.shape[0])

In [ ]:
emp_df

name    location  salary        0        1      2
0    amit      mumbai    23.0      NaN      NaN    NaN
1  justin  california   500.0      NaN      NaN    NaN
2   jason          sf    80.0      NaN      NaN    NaN
3     NaN         NaN     NaN  abhijit  atlanta  300.0
4     NaN         NaN     NaN    karan     roha    4.0
5     NaN         NaN     NaN  rishabh    bihar    2.0

In [ ]:
newdf = pd.DataFrame([['abhijit','atlanta',300],['karan','roha',4],['rishabh','bihar',2]],columns=['name','location','salary'])

In [ ]:
iemp_df = emp_df._append(newdf,ignore_index=True)

In [ ]:
iemp_df

name    location  salary
0     amit      mumbai      23
1   justin  california     400
2    jason          sf      80
3  abhijit     atlanta     300
4    karan        roha       4
5  rishabh       bihar       2

In [7]:
cemp_df = pd.concat([emp_df,newdf]).reset_index(drop=True)
cemp_df

NameError: name 'pd' is not defined

In [ ]:
cemp_df.drop(cemp_df.index[5:])
cemp_df

name    location  salary
0     amit      mumbai      23
1   justin  california     400
2    jason          sf      80
3  abhijit     atlanta     300
4    karan        roha       4
5  rishabh       bihar       2

In [ ]:

mydf = emp_df.iloc[[0,1,4]]

mydf


IndexError: positional indexers are out-of-bounds

- iloc are used to select rows of given idices

In [ ]:
new_df = emp_df.drop([1,3],axis=0)

KeyError: '[3] not found in axis'

In [ ]:
new_df

name location  salary        0      1    2
0   amit   mumbai    23.0      NaN    NaN  NaN
2  jason       sf    80.0      NaN    NaN  NaN
4    NaN      NaN     NaN    karan   roha  4.0
5    NaN      NaN     NaN  rishabh  bihar  2.0

In [ ]:
x1 = np.array(emp_df.location)

In [ ]:
x1

array(['mumbai', 'california', 'sf', nan, nan, nan], dtype=object)

In [ ]:
# add column tak values are going to be 10 % of salary column

x3 = cemp_df.salary
x4 = x3 /10


In [ ]:
x4

0     2.3
1    40.0
2     8.0
3    30.0
4     0.4
5     0.2
Name: salary, dtype: float64

In [ ]:
cemp_df['tax']=x4

In [ ]:
cemp_df

name    location  salary   tax
0     amit      mumbai      23   2.3
1   justin  california     400  40.0
2    jason          sf      80   8.0
3  abhijit     atlanta     300  30.0
4    karan        roha       4   0.4
5  rishabh       bihar       2   0.2

In [ ]:
sal = emp_df[['name','salary']]

In [ ]:
sal

name  salary
0    amit      23
1  justin     400
2   jason      80

In [8]:
sal = cemp_df.drop('tax',axis=1)
sal

NameError: name 'cemp_df' is not defined

In [ ]:
stu_names = ['amit','charanjeet','vibha','ruchika']

stu_marks = [68,43,55,78]

students = {'name': stu_names ,'makrks':stu_marks}

In [ ]:
stu_df = pd.DataFrame(students)
stu_df

name  makrks
0        amit      68
1  charanjeet      43
2       vibha      55
3     ruchika      78

In [ ]:
import os


In [ ]:
data = pd.read_excel('/content/CDAC_DataBook.xlsx', sheet_name='ERPData')
data

MaterialID Location  Quantity
0     TMI-43T    MWH-4        34
1     AXCP-78    MWH-1        67
2     LXCV-21    MWH-2        27
3     AXCP-78    MWH-5        65
4     AXCP-78    MWH-4        36
5     TMI-43T    MWH-4        78
6     TMI-43T    MWH-4        31
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
9     TMI-43T    MWH-1       120
10    SDRT-67    MWH-1        34
11    SDRT-67    MWH-4        58
12    TMI-43T    MWH-4        76
13    TMI-43T    MWH-4        32
14    TMI-43T    MWH-3        65
15    GCVB-79    MWH-2        87
16    SDRT-67    MWH-5        12
17    SDRT-67    MWH-5       102
18    TMI-43T    MWH-4        34
19    TMI-43T    MWH-4        52
20    TMI-43T    MWH-4        39
21    TMI-43T    MWH-4        75
22    DDBN-89    MWH-4        48
23    DDBN-89    MWH-5        71
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
26    DDBN-89    MWH-1        57
27    LXCV-21    MWH-5        83
28    LXCV-21    MWH-5        34
29    LXCV-21    MWH-5        57
30    DDBN-89    MWH-4        27
31    TMI-43T    MWH-4        65
32    TMI-43T    MWH-4        43
33    TMI-43T    MWH-5       112
34    GCVB-79    MWH-5        26
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70
39    AXCP-78    MWH-1       145
40    DDBN-89    MWH-1        34
41    SDRT-67    MWH-1        57
42    SDRT-67    MWH-2        31
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
47    AXCP-78    MWH-3        29
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39

In [ ]:
unique = data['Location'].unique()

SyntaxError: invalid syntax (<ipython-input-32-6717bc65b23f>, line 1)

In [ ]:
len(unique)

5

In [ ]:
new_df = pd.DataFrame([['LxCv-23','MWH',40],['aXCP-78','WDS',50]])

In [ ]:
new_df

0    1   2
0  LxCv-23  MWH  40
1  aXCP-78  WDS  50

- imp

In [ ]:
new_df.columns = data.columns
new_df

MaterialID Location  Quantity
0    LxCv-23      MWH        40
1    aXCP-78      WDS        50

In [ ]:
m100 = np.where(data.Quantity >=100)

In [ ]:
len(m100[0])

6

In [ ]:
data.iloc[m100[0]]

MaterialID Location  Quantity
9     TMI-43T    MWH-1       120
17    SDRT-67    MWH-5       102
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
33    TMI-43T    MWH-5       112
39    AXCP-78    MWH-1       145

In [ ]:
df5 = data [(data['MaterialID']=='AXCP-78') & ((data['Location']=='MWH-1') | (data['Location']=='MWH-2')) ]
df5

MaterialID Location  Quantity
1     AXCP-78    MWH-1        67
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
39    AXCP-78    MWH-1       145
46    AXCP-78    MWH-2        85
48    AXCP-78    MWH-1        75

### Data cleaning & validation

- DAta clearning
  - values are missing .




In [ ]:
data_df = pd.read_excel("/content/PandasExamples.xlsx",sheet_name='EmpInfo')
data_df

Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
3    Arjun  A342      NaN  RF453432
4    Rishi  R475    Prodn  DF453278
5   Chetan   NaN      NaN  ER534867
6   Deepak   NaN  Quality  RF453432

1. nan in python represents missing values.



- missing values in deptt column



In [ ]:

c1 = np.where(data_df['Deptt'].isnull())

In [ ]:
c1

(array([3, 5]),)

In [ ]:
c2 = np.where((data_df['Deptt'].isnull()| (data_df['EmpID'].isnull())))
c2

(array([3, 5, 6]),)

In [ ]:
data_df['Name'].iloc[c2[0]]

3     Arjun
5    Chetan
6    Deepak
Name: Name, dtype: object


- df.dropna() : drop all rows with null values in a dataframe

In [ ]:
nn_df = data_df.dropna()

In [ ]:
nn_df

Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
4    Rishi  R475    Prodn  DF453278

In [ ]:
t1 = np.where(data_df['Deptt'].isnull())[0]
df = data_df.drop(t1,axis=0)

In [ ]:
df

Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
4    Rishi  R475    Prodn  DF453278
6   Deepak   NaN  Quality  RF453432

- Alternate method

In [ ]:
df = data_df.dropna(subset=['Deptt'])
df

Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
4    Rishi  R475    Prodn  DF453278
6   Deepak   NaN  Quality  RF453432

- duplicate values

In [ ]:
t1 = np.where(data_df['Passport'].duplicated(keep=False))
t1

(array([0, 2, 3, 4, 6]),)

- t1: rows where there are passpoed id are repeated

In [ ]:
t2 = np.where(~data_df['Passport'].duplicated(keep=False))
t2

(array([1, 5]),)

- data validation : age of employees must be above 18 years
- question : passport id must meet the criteria ( char / number combinations)

In [ ]:
q3 = np.where((data.Quantity <=50)|(data.Quantity>=100))
q3

(array([ 0,  2,  4,  6,  7,  8,  9, 10, 13, 16, 17, 18, 20, 22, 24, 25, 28,
        30, 32, 33, 34, 35, 36, 39, 40, 42, 43, 44, 47, 49]),)

In [ ]:
# Assuming 'df' is your DataFrame with a 'quantity' column
result = data[(data['Quantity'] < 50) | (data['Quantity'] > 100)]
resul



NameError: name 'resul' is not defined

- var_name = df.groupby('col name') : group according to col name in dataframe.

- returns dictionary
- var_name.groups

In [ ]:
grp1 =data.groupby('Location')
grp1.groups

{'MWH-1': [1, 9, 10, 24, 25, 26, 39, 40, 41, 48, 49], 'MWH-2': [2, 7, 8, 15, 35, 36, 42, 45, 46], 'MWH-3': [14, 43, 44, 47], 'MWH-4': [0, 4, 5, 6, 11, 12, 13, 18, 19, 20, 21, 22, 30, 31, 32], 'MWH-5': [3, 16, 17, 23, 27, 28, 29, 33, 34, 37, 38]}

In [ ]:
for p1 ,p2 in grp1:
    print(p1)
    print(p2)

MWH-1
   MaterialID Location  Quantity
1     AXCP-78    MWH-1        67
9     TMI-43T    MWH-1       120
10    SDRT-67    MWH-1        34
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
26    DDBN-89    MWH-1        57
39    AXCP-78    MWH-1       145
40    DDBN-89    MWH-1        34
41    SDRT-67    MWH-1        57
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39
MWH-2
   MaterialID Location  Quantity
2     LXCV-21    MWH-2        27
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
15    GCVB-79    MWH-2        87
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
42    SDRT-67    MWH-2        31
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
MWH-3
   MaterialID Location  Quantity
14    TMI-43T    MWH-3        65
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
47    AXCP-78    MWH-3        29
MWH-4
   MaterialID Location  Quantity
0     TMI-43T    MWH-4        34
4     AXCP-78    MW

- show a particular group

In [ ]:
grp1.get_group('MWH-2')

MaterialID Location  Quantity
2     LXCV-21    MWH-2        27
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
15    GCVB-79    MWH-2        87
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
42    SDRT-67    MWH-2        31
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85

In [ ]:
grp1.agg(np.size)

MaterialID  Quantity
Location                      
MWH-1             11        11
MWH-2              9         9
MWH-3              4         4
MWH-4             15        15
MWH-5             11        11

In [ ]:
grp1['Quantity'].sum()

Location
MWH-1    889
MWH-2    397
MWH-3    174
MWH-4    728
MWH-5    697
Name: Quantity, dtype: int64

In [ ]:
grp1.agg(np.sum)

MaterialID  Quantity
Location                                                             
MWH-1     AXCP-78TMI-43TSDRT-67AXCP-78AXCP-78DDBN-89AXCP...       889
MWH-2     LXCV-21TMI-43TGCVB-79GCVB-79GCVB-79GCVB-79SDRT...       397
MWH-3                          TMI-43TDDBN-89LXCV-21AXCP-78       174
MWH-4     TMI-43TAXCP-78TMI-43TTMI-43TSDRT-67TMI-43TTMI-...       728
MWH-5     AXCP-78SDRT-67SDRT-67DDBN-89LXCV-21LXCV-21LXCV...       697

In [ ]:
grp1['Quantity'].mean()

Location
MWH-1    80.818182
MWH-2    44.111111
MWH-3    43.500000
MWH-4    48.533333
MWH-5    63.363636
Name: Quantity, dtype: float64

In [ ]:
grp1_df = grp1.Quantity.agg([np.sum,np.mean])

In [ ]:
grp1_df.iloc[np.where(grp1_df.index=='MWH-4')]

sum       mean
Location                
MWH-4     728  48.533333



grp2 = data.groupby(['Location','MaterialID'])
grp2.groups

- here location is first so it is **primary key** , **MaterialID** is secondary key .





In [ ]:
grp2 = data.groupby(['Location','MaterialID'])
grp2.groups

{('MWH-1', 'AXCP-78'): [1, 24, 25, 39, 48], ('MWH-1', 'DDBN-89'): [26, 40, 49], ('MWH-1', 'SDRT-67'): [10, 41], ('MWH-1', 'TMI-43T'): [9], ('MWH-2', 'AXCP-78'): [46], ('MWH-2', 'DDBN-89'): [45], ('MWH-2', 'GCVB-79'): [8, 15, 35, 36], ('MWH-2', 'LXCV-21'): [2], ('MWH-2', 'SDRT-67'): [42], ('MWH-2', 'TMI-43T'): [7], ('MWH-3', 'AXCP-78'): [47], ('MWH-3', 'DDBN-89'): [43], ('MWH-3', 'LXCV-21'): [44], ('MWH-3', 'TMI-43T'): [14], ('MWH-4', 'AXCP-78'): [4], ('MWH-4', 'DDBN-89'): [22, 30], ('MWH-4', 'SDRT-67'): [11], ('MWH-4', 'TMI-43T'): [0, 5, 6, 12, 13, 18, 19, 20, 21, 31, 32], ('MWH-5', 'AXCP-78'): [3, 37, 38], ('MWH-5', 'DDBN-89'): [23], ('MWH-5', 'GCVB-79'): [34], ('MWH-5', 'LXCV-21'): [27, 28, 29], ('MWH-5', 'SDRT-67'): [16, 17], ('MWH-5', 'TMI-43T'): [33]}

In [ ]:
grp2.agg(np.sum)

Quantity
Location MaterialID          
MWH-1    AXCP-78          548
         DDBN-89          130
         SDRT-67           91
         TMI-43T          120
MWH-2    AXCP-78           85
         DDBN-89           69
         GCVB-79          156
         LXCV-21           27
         SDRT-67           31
         TMI-43T           29
MWH-3    AXCP-78           29
         DDBN-89           38
         LXCV-21           42
         TMI-43T           65
MWH-4    AXCP-78           36
         DDBN-89           75
         SDRT-67           58
         TMI-43T          559
MWH-5    AXCP-78          200
         DDBN-89           71
         GCVB-79           26
         LXCV-21          174
         SDRT-67          114
         TMI-43T          112

In [ ]:
data_pune = pd.read_excel('/content/PandasExamples.xlsx',sheet_name='Pune')
data_mumbai = pd.read_excel('/content/PandasExamples.xlsx',sheet_name='Mumbai')
data_pune,data_mumbai

(      Name      Subject Grade
 0   Rakesh       Python     A
 1    Manoj     MLPython     C
 2  Vaibhav   Statistics     B
 3   Hitesh   CommSkills     A
 4   Suyash  ProjectMgmt     B,
        Name     Subject Grade
 0   Vaibhav   Six Sigma     A
 1   Deepika  Statistics     B
 2     Arjun  CommSkills     A
 3    Chetan      Python     A
 4  Abhishek    MLPython     B)

In [ ]:
pd.merge(data_pune,data_mumbai ,on='Subject')

Name_x     Subject Grade_x    Name_y Grade_y
0   Rakesh      Python       A    Chetan       A
1    Manoj    MLPython       C  Abhishek       B
2  Vaibhav  Statistics       B   Deepika       B
3   Hitesh  CommSkills       A     Arjun       A

In [ ]:

pd.merge(data_pune,data_mumbai ,on='Subject',how='inner')

Name_x     Subject Grade_x    Name_y Grade_y
0   Rakesh      Python       A    Chetan       A
1    Manoj    MLPython       C  Abhishek       B
2  Vaibhav  Statistics       B   Deepika       B
3   Hitesh  CommSkills       A     Arjun       A


- pd.merge(data_pune,data_mumbai ,on='Subject')

- above command picks common subjects from df1 , df2  default how is inner

-

Name_x      Subject Grade_x    Name_y Grade_y
0   Rakesh       Python       A    Chetan       A
1    Manoj     MLPython       C  Abhishek       B
2  Vaibhav   Statistics       B   Deepika       B
3   Hitesh   CommSkills       A     Arjun       A
4   Suyash  ProjectMgmt       B       NaN     NaN
5      NaN    Six Sigma     NaN   Vaibhav       A

In [ ]:

pd.merge(data_pune,data_mumbai ,on =['Subject','Grade'],how='inner')

Name_x     Subject Grade   Name_y
0   Rakesh      Python     A   Chetan
1  Vaibhav  Statistics     B  Deepika
2   Hitesh  CommSkills     A    Arjun

In [ ]:
pd.merge(data_pune,data_mumbai ,on =['Subject','Grade'],how='outer')

Name_x      Subject Grade    Name_y
0   Rakesh       Python     A    Chetan
1    Manoj     MLPython     C       NaN
2  Vaibhav   Statistics     B   Deepika
3   Hitesh   CommSkills     A     Arjun
4   Suyash  ProjectMgmt     B       NaN
5      NaN    Six Sigma     A   Vaibhav
6      NaN     MLPython     B  Abhishek

In [ ]:


pd.merge(data_pune,data_mumbai,on=['Subject'],how='left')

Name_x      Subject Grade_x    Name_y Grade_y
0   Rakesh       Python       A    Chetan       A
1    Manoj     MLPython       C  Abhishek       B
2  Vaibhav   Statistics       B   Deepika       B
3   Hitesh   CommSkills       A     Arjun       A
4   Suyash  ProjectMgmt       B       NaN     NaN

In [ ]:
data_mumbai

Name     Subject Grade
0   Vaibhav   Six Sigma     A
1   Deepika  Statistics     B
2     Arjun  CommSkills     A
3    Chetan      Python     A
4  Abhishek    MLPython     B

In [ ]:
data_pune

Name      Subject Grade
0   Rakesh       Python     A
1    Manoj     MLPython     C
2  Vaibhav   Statistics     B
3   Hitesh   CommSkills     A
4   Suyash  ProjectMgmt     B

In [ ]:
pd.merge(data_pune,data_mumbai)

In [ ]:
x1 = np.array ([2,2,4,3,5,3,2,45,67,6])


In [ ]:
x2 = sorted(x1)
x3 = np.argsort(x1)  # index of sorted elements
print (x2,x3)

[2, 2, 2, 3, 3, 4, 5, 6, 45, 67] [0 1 6 3 5 2 4 9 7 8]


In [ ]:
df1 = data.sort_values(['Quantity'])
df4 = data.sort_values(['Quantity'],ascending=False)

df1,df4

(   MaterialID Location  Quantity
 8     GCVB-79    MWH-2        10
 16    SDRT-67    MWH-5        12
 34    GCVB-79    MWH-5        26
 2     LXCV-21    MWH-2        27
 30    DDBN-89    MWH-4        27
 36    GCVB-79    MWH-2        28
 47    AXCP-78    MWH-3        29
 7     TMI-43T    MWH-2        29
 42    SDRT-67    MWH-2        31
 6     TMI-43T    MWH-4        31
 35    GCVB-79    MWH-2        31
 13    TMI-43T    MWH-4        32
 0     TMI-43T    MWH-4        34
 28    LXCV-21    MWH-5        34
 40    DDBN-89    MWH-1        34
 18    TMI-43T    MWH-4        34
 10    SDRT-67    MWH-1        34
 4     AXCP-78    MWH-4        36
 43    DDBN-89    MWH-3        38
 20    TMI-43T    MWH-4        39
 49    DDBN-89    MWH-1        39
 44    LXCV-21    MWH-3        42
 32    TMI-43T    MWH-4        43
 22    DDBN-89    MWH-4        48
 19    TMI-43T    MWH-4        52
 29    LXCV-21    MWH-5        57
 26    DDBN-89    MWH-1        57
 41    SDRT-67    MWH-1        57
 11    SDRT-67

In [ ]:
df5 = data.sort_values(['Location','MaterialID','Quantity'])
df5

MaterialID Location  Quantity
1     AXCP-78    MWH-1        67
48    AXCP-78    MWH-1        75
25    AXCP-78    MWH-1       109
39    AXCP-78    MWH-1       145
24    AXCP-78    MWH-1       152
40    DDBN-89    MWH-1        34
49    DDBN-89    MWH-1        39
26    DDBN-89    MWH-1        57
10    SDRT-67    MWH-1        34
41    SDRT-67    MWH-1        57
9     TMI-43T    MWH-1       120
46    AXCP-78    MWH-2        85
45    DDBN-89    MWH-2        69
8     GCVB-79    MWH-2        10
36    GCVB-79    MWH-2        28
35    GCVB-79    MWH-2        31
15    GCVB-79    MWH-2        87
2     LXCV-21    MWH-2        27
42    SDRT-67    MWH-2        31
7     TMI-43T    MWH-2        29
47    AXCP-78    MWH-3        29
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
14    TMI-43T    MWH-3        65
4     AXCP-78    MWH-4        36
30    DDBN-89    MWH-4        27
22    DDBN-89    MWH-4        48
11    SDRT-67    MWH-4        58
6     TMI-43T    MWH-4        31
13    TMI-43T    MWH-4        32
0     TMI-43T    MWH-4        34
18    TMI-43T    MWH-4        34
20    TMI-43T    MWH-4        39
32    TMI-43T    MWH-4        43
19    TMI-43T    MWH-4        52
31    TMI-43T    MWH-4        65
21    TMI-43T    MWH-4        75
12    TMI-43T    MWH-4        76
5     TMI-43T    MWH-4        78
3     AXCP-78    MWH-5        65
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70
23    DDBN-89    MWH-5        71
34    GCVB-79    MWH-5        26
28    LXCV-21    MWH-5        34
29    LXCV-21    MWH-5        57
27    LXCV-21    MWH-5        83
16    SDRT-67    MWH-5        12
17    SDRT-67    MWH-5       102
33    TMI-43T    MWH-5       112